name: Update the Prisma Cloud policies 

on:
  workflow_dispatch: # on button click
  # pull_request:
  # push:
  #   branches:
  #     - main

env:
  PRISMA_API_URL: ${{ secrets.PRISMA_API_URL }}
  PRISMA_ACCESS_KEY: ${{ secrets.PRISMA_ACCESS_KEY }}
  PRISMA_SECRET_KEY: ${{ secrets.PRISMA_SECRET_KEY }}

jobs:
  update_prisma_cloud_policies:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 
        run: |
          python policy_updater.py --debug